### ISSUE TITLE
DualQuaternion.setScrewParameters doesn't use passed in parameters

### ISSUE THREAD

**Issue by ryancu7** [artisynth/artisynth_core#13]
Looking at maspack.matrix.DualQuaternion.setScrewParameters(), `Vector3d l` and `Vector3d m` are parameters of this function but they are not used. Instead, the function uses the member variables `ltmp` and `mtmp`. Currently, all uses of setScrewParameters involve passing `ltmp` and `mtmp` as the corresponding arguments so no bugs are observed. Nevertheless, the function body should be changed, with `l` replacing `ltmp` and `m` replacing `mtmp`.

**Comment by JohnLloyd7** [comment]
Thanks ryancu7, good catch! Fix has been made, along with removal of some of the temporary member variables in DualQuaternion.
