### ISSUE TITLE
 Exception when contact pressure display range has a lower bound > 0

### ISSUE THREAD

**Issue by bsagl** [artisynth/artisynth_core#14]
Hi all,

I seem to have found a bug in the code for rendering contact
pressures. It seems that sometimes when using a fixed display range
with a lower bound > 0, I get an exception like this:

java.lang.NullPointerException
         at
maspack.render.GL.GL3.ColorBufferPutter.putColor(ColorBufferPutter.java:16)
         at
maspack.render.GL.GL3.GL3SharedRenderObjectVertices.fillVertexVBO(GL3SharedRenderObjectVertices.java:202)
         at
maspack.render.GL.GL3.GL3SharedRenderObjectVertices.buildVertices(GL3SharedRenderObjectVertices.java:141)
         at
maspack.render.GL.GL3.GL3SharedRenderObjectBase.maybeUpdateVertices(GL3SharedRenderObjectBase.java:172)
         at
maspack.render.GL.GL3.GL3SharedRenderObjectPrimitives.maybeUpdate(GL3SharedRenderObjectPrimitives.java:63)
         at
maspack.render.GL.GL3.GL3SharedRenderObjectPrimitives.generate(GL3SharedRenderObjectPrimitives.java:306)
         at
maspack.render.GL.GL3.GL3SharedRenderObjectManager.getPrimitives(GL3SharedRenderObjectManager.java:39)
         at
maspack.render.GL.GL3.GL3SharedResources.getPrimitives(GL3SharedResources.java:50)
         at
maspack.render.GL.GL3.GL3RenderObjectManager.getPrimitives(GL3RenderObjectManager.java:107)
         at
maspack.render.GL.GL3.GL3Viewer.drawTriangles(GL3Viewer.java:1924)
         at maspack.render.GL.GLViewer.drawTriangles(GLViewer.java:4665)
         at maspack.render.GL.GLViewer.drawTriangles(GLViewer.java:4660)
         at
artisynth.core.mechmodels.CollisionRenderer.render(CollisionRenderer.java:537)
         at
artisynth.core.mechmodels.CollisionHandler.render(CollisionHandler.java:1700)
         at
artisynth.core.mechmodels.CollisionHandler.render(CollisionHandler.java:1690)
         at maspack.render.RenderList.renderList(RenderList.java:419)

I was able to reproduce the problem in the demos. Run
artisynth.demos.tutorial.ContactPressureRender, open the navigation
panel, and navigate to

models > mech > collisionManager > behaviors > models#ball-models#sheet

Then right click, "Edit properties ...", and in the "interval"
property for the colrMapRange, set the lower bound to 1000.

thanks!

**Comment by JohnLloyd7** [comment]
Fixed. Rendered pressure values which were lower than the lower bound needed to be clipped to the lower bound in order to prevent negative color indices.

cheers,

J
