### ISSUE TITLE
issue about length computation in multipointspring

### ISSUE THREAD

**Issue by callmebigbig** [artisynth/artisynth_core#17]
/**
       * Updates the unit vector and length of this segment.
       */
      double updateU () {
         myUvec.sub (myPntA.getPosition(), myPntB.getPosition());
         myLength = myUvec.norm();
         if (myLength != 0) {
            myUvec.scale (1 / myLength);
         }
         return myLength;
      }

The update function computes the uvec of segment and changes the mylength of the segment to the distance between pntA and pntB instead of the sum of distance between every knots, leading to the wrong result when getting the final string length.

**Comment by JohnLloyd7** [comment]
Thanks for your comment. If the segment is a WrapSegment, then updateU() is not actually called for the segment itself. Instead, updateU() is called for its subsegments (to compute to the u directions), and myLength for the WrapSegment  is not changed. See MultiPointSpring.computeLength(), starting at line 2886. Wrap segment lengths are computed within the WrapSegment methods advanceKnotPositions() and initializeStrand().

**Comment by callmebigbig** [comment]
I set an outputprobe to read the spring length and it will call the geLength(), and computeLength (boolean activeOnly) will be called by getLength(). Then the updateU function will work and change the myLength value. The myLength calculated in wrapsegment.computeLength() will be change. I suggest to use a new intermediate variable in the updateU function.

**Comment by JohnLloyd7** [comment]
If a WrapSegment is in contact with a wrapping surface, then it will contain subsegments, and so updateU() will not be called and the previously computed value of myLength will be left unchanged. If the segment is not in contact, updateU() will be called, but the resulting length computation will be correct. The relevant code in computeLength(boolean) is this:
```
   if (seg.hasSubSegments()) {
      // wrap segment in contact; updateU() only called for subsegments with no effect on myLength
      for (SubSegment ss=seg.firstSubSegment(); ss!=null; ss=ss.myNext) {
         ss.updateU();
      }
   }
   else {
      // segment is not a WrapSegment or is not in contact
      seg.updateU();
   }
```

**Comment by callmebigbig** [comment]
Ok, i see . Then I have no more question. Thank you for your reply!

**Comment by JohnLloyd7** [comment]
Sure. I agree that the implementation is confusing. I've added some comments that will get pushed in the next update.
